# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=255)),
                ('e_startdate', models.DateTimeField()),
                ('e_enddate', models.DateTimeField()),
                ('e_place', models.TextField()),
                ('e_description', models.TextField()),
                ('e_deadline', models.DateTimeField()),
                ('e_postdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=20)),
                ('m_email', models.CharField(max_length=255)),
                ('m_last_active', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_timestamp', models.DateTimeField()),
                ('n_content', models.TextField()),
                ('n_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_from', to='main.Member')),
                ('n_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_to', to='main.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_is_paid', models.CharField(default='N', max_length=1)),
                ('p_eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('p_memberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='e_organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member'),
        ),
        migrations.AddField(
            model_name='admin',
            name='adm_eventid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
        migrations.AddField(
            model_name='admin',
            name='adm_memberid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member'),
        ),
    ]
