# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 02:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20160604_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='p_eventid',
            new_name='p_event',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='p_memberid',
            new_name='p_member',
        ),
        migrations.AddField(
            model_name='event',
            name='e_participant',
            field=models.ManyToManyField(related_name='e_participant', through='main.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='e_organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
