# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20160611_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='adm_eventid',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='adm_memberid',
        ),
        migrations.AddField(
            model_name='event',
            name='e_admin',
            field=models.ManyToManyField(related_name='e_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
