# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160611_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='n_read',
            field=models.BooleanField(default=False),
        ),
    ]
